### ISSUE TITLE
Build fails because env variable PYTORCH_RCCL_LIBRARIES not set

### ISSUE THREAD

**Issue by navti** [rocm-arch/python-pytorch-rocm#37] opened 2022-04-14 22:02 UTC
The build fails. Environment variable PYTORCH_RCCL_LIBRARIES is set as NOTFOUND. Build error screenshot is attached.
![builderror](https://user-images.githubusercontent.com/13915191/163483415-715f3f5e-d363-4503-b754-350ad096c696.png)

**Comment by navti** [comment] 2022-04-17 06:55
My apologies. Here are the last few lines of build log. Environment variable PYTORCH_RCCL_LIBRARIES is set as NOTFOUND.
```-- Configuring done  
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTORCH_RCCL_LIBRARIES
    linked by target "torch_hip" in directory /home/codez/.cache/yay/python-pytorch-rocm/src/pytorch-1.11.0-rocm/caffe2
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Building wheel torch-1.11.0a0+gitbc2c6ed
-- Building version 1.11.0a0+gitbc2c6ed
cmake -GNinja -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/codez/.cache/yay/python-pytorch-rocm/src/pytorch-1.11.0-rocm/torch -DCMAKE_PREFIX_PATH=/usr/lib/python3.10/site-packages -DNUMPY_INCLUDE_DIR=/usr/lib/python3.10/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/usr/bin/python -DPYTHON_INCLUDE_DIR=/usr/include/python3.10 -DPYTHON_LIBRARY=/usr/lib/libpython3.10.so.1.0 -DTORCH_BUILD_VERSION=1.11.0a0+gitbc2c6ed -DUSE_CUDA=0 -DUSE_CUDNN=0 -DUSE_NUMPY=True -DUSE_ROCM=1 /home/codez/.cache/yay/python-pytorch-rocm/src/pytorch-1.11.0-rocm
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: python-pytorch-rocm
```

**Comment by acxz** [comment] 2022-07-03 17:42
@navti I'm not able to reproduce this with the latest pytorch version. Maybe the latest version has resolved this? 

Can you try again? I'll go ahead and close this issue for now, and reopen it if/when someone else can reproduce this error.

**Closed by acxz** 2022-07-03 17:42 UTC
Labels: build error
