### ISSUE TITLE
Errors occur when finding ROCclrConfig.cmake or rocclr-config.cmake

### ISSUE THREAD

**Issue by petronny** [rocm-arch/python-pytorch-rocm#27] opened 2021-05-09 11:28 UTC
```
...
caffe2/utils/math/reduce.cu -> caffe2/utils/math/hip/reduce.hip ok
caffe2/utils/math/broadcast.cu -> caffe2/utils/math/hip/broadcast.hip ok
caffe2/utils/math/elementwise.cu -> caffe2/utils/math/hip/elementwise.hip ok
caffe2/utils/math/reduce.cuh -> caffe2/utils/math/hip/reduce.cuh ok
caffe2/utils/math/transpose.cu -> caffe2/utils/math/hip/transpose.hip ok
Re-run cmake no build system arguments
-- The CXX compiler identification is GNU 10.2.0
-- The C compiler identification is GNU 10.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Not forcing any particular BLAS to be found
-- Performing Test COMPILER_WORKS
-- Performing Test COMPILER_WORKS - Success
-- Performing Test SUPPORT_GLIBCXX_USE_C99
-- Performing Test SUPPORT_GLIBCXX_USE_C99 - Success
-- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED
-- Performing Test CAFFE2_EXCEPTION_PTR_SUPPORTED - Success
-- std::exception_ptr is supported.
-- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING
-- Performing Test CAFFE2_NEED_TO_TURN_OFF_DEPRECATION_WARNING - Success
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX2_EXTENSIONS - Success
-- Current compiler supports avx2 extension. Will build perfkernels.
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX512_EXTENSIONS
-- Performing Test CAFFE2_COMPILER_SUPPORTS_AVX512_EXTENSIONS - Success
-- Current compiler supports avx512f extension. Will build fbgemm.
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_SUPPORTS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC - Success
-- Building using own protobuf under third_party per request.
-- Use custom protobuf build.
-- 
-- 3.11.4.0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Performing Test protobuf_HAVE_BUILTIN_ATOMICS
-- Performing Test protobuf_HAVE_BUILTIN_ATOMICS - Success
-- Caffe2 protobuf include directory: $<BUILD_INTERFACE:/build/python-pytorch-rocm/src/pytorch-1.7.1-rocm/third_party/protobuf/src>$<INSTALL_INTERFACE:include>
-- Trying to find preferred BLAS backend of choice: MKL
-- MKL_THREADING = OMP
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
CMake Warning (dev) at /usr/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_C)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindOpenMP.cmake:565 (find_package_handle_standard_args)
  cmake/Modules/FindMKL.cmake:213 (FIND_PACKAGE)
  cmake/Modules/FindMKL.cmake:307 (CHECK_ALL_LIBRARIES)
  cmake/Dependencies.cmake:136 (find_package)
  CMakeLists.txt:513 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_CXX)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindOpenMP.cmake:565 (find_package_handle_standard_args)
  cmake/Modules/FindMKL.cmake:213 (FIND_PACKAGE)
  cmake/Modules/FindMKL.cmake:307 (CHECK_ALL_LIBRARIES)
  cmake/Dependencies.cmake:136 (find_package)
  CMakeLists.txt:513 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for cblas_sgemm
-- Looking for cblas_sgemm - found
-- MKL libraries: /opt/intel/mkl/lib/intel64/libmkl_intel_lp64.so;/opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so;/opt/intel/mkl/lib/intel64/libmkl_core.so;-fopenmp;/usr/lib/libpthread.so;/usr/lib/libm.so;/usr/lib/libdl.so
-- MKL include directory: /opt/intel/mkl/include
-- MKL OpenMP type: GNU
-- MKL OpenMP library: -fopenmp
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Brace yourself, we are building NNPACK
-- Performing Test NNPACK_ARCH_IS_X86_32
-- Performing Test NNPACK_ARCH_IS_X86_32 - Failed
-- Found PythonInterp: /usr/bin/python (found version "3.9.4") 
-- NNPACK backend is x86-64
-- Caffe2: Found gflags with new-style gflags target.
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Found glog: /usr/include  
-- Caffe2: Found glog (include: /usr/include, library: /usr/lib/libglog.so)
CMake Deprecation Warning at third_party/googletest/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at third_party/googletest/googlemock/CMakeLists.txt:42 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at third_party/googletest/googletest/CMakeLists.txt:49 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Failed to find LLVM FileCheck
-- Found Git: /usr/bin/git (found version "2.31.1") 
-- git Version: v1.4.0-505be96a
-- Version: 1.4.0
-- Performing Test HAVE_CXX_FLAG_STD_CXX11
-- Performing Test HAVE_CXX_FLAG_STD_CXX11 - Success
-- Performing Test HAVE_CXX_FLAG_WALL
-- Performing Test HAVE_CXX_FLAG_WALL - Success
-- Performing Test HAVE_CXX_FLAG_WEXTRA
-- Performing Test HAVE_CXX_FLAG_WEXTRA - Success
-- Performing Test HAVE_CXX_FLAG_WSHADOW
-- Performing Test HAVE_CXX_FLAG_WSHADOW - Success
-- Performing Test HAVE_CXX_FLAG_WERROR
-- Performing Test HAVE_CXX_FLAG_WERROR - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC
-- Performing Test HAVE_CXX_FLAG_PEDANTIC - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS - Success
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 - Failed
-- Performing Test HAVE_CXX_FLAG_WFLOAT_EQUAL
-- Performing Test HAVE_CXX_FLAG_WFLOAT_EQUAL - Success
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED_DECLARATIONS
-- Performing Test HAVE_CXX_FLAG_WNO_DEPRECATED_DECLARATIONS - Success
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WD654
-- Performing Test HAVE_CXX_FLAG_WD654 - Failed
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY - Failed
-- Performing Test HAVE_CXX_FLAG_COVERAGE
-- Performing Test HAVE_CXX_FLAG_COVERAGE - Success
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Performing Test COMPILER_SUPPORTS_AVX512
-- Performing Test COMPILER_SUPPORTS_AVX512 - Success
CMake Warning (dev) at /usr/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_C)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindOpenMP.cmake:565 (find_package_handle_standard_args)
  third_party/fbgemm/CMakeLists.txt:59 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenMP_C: -fopenmp (found version "4.5") 
CMake Warning (dev) at /usr/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_CXX)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindOpenMP.cmake:565 (find_package_handle_standard_args)
  third_party/fbgemm/CMakeLists.txt:59 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
CMake Warning at third_party/fbgemm/CMakeLists.txt:61 (message):
  OpenMP found! OpenMP_C_INCLUDE_DIRS =


CMake Warning at third_party/fbgemm/CMakeLists.txt:136 (message):
  ==========


CMake Warning at third_party/fbgemm/CMakeLists.txt:137 (message):
  CMAKE_BUILD_TYPE = Release


CMake Warning at third_party/fbgemm/CMakeLists.txt:138 (message):
  CMAKE_CXX_FLAGS_DEBUG is -g


CMake Warning at third_party/fbgemm/CMakeLists.txt:139 (message):
  CMAKE_CXX_FLAGS_RELEASE is -O3 -DNDEBUG


CMake Warning at third_party/fbgemm/CMakeLists.txt:140 (message):
  ==========


-- Performing Test __CxxFlag__fno_threadsafe_statics
-- Performing Test __CxxFlag__fno_threadsafe_statics - Success
-- Performing Test __CxxFlag__fno_semantic_interposition
-- Performing Test __CxxFlag__fno_semantic_interposition - Success
-- Performing Test __CxxFlag__fmerge_all_constants
-- Performing Test __CxxFlag__fmerge_all_constants - Success
** AsmJit Summary **
   ASMJIT_DIR=/build/python-pytorch-rocm/src/pytorch-1.7.1-rocm/third_party/fbgemm/third_party/asmjit
   ASMJIT_TEST=FALSE
   ASMJIT_TARGET_TYPE=STATIC
   ASMJIT_DEPS=pthread;rt
   ASMJIT_LIBS=asmjit;pthread;rt
   ASMJIT_CFLAGS=-DASMJIT_STATIC
   ASMJIT_PRIVATE_CFLAGS=-Wall;-Wextra;-fno-math-errno;-fno-threadsafe-statics;-fno-semantic-interposition;-DASMJIT_STATIC
   ASMJIT_PRIVATE_CFLAGS_DBG=
   ASMJIT_PRIVATE_CFLAGS_REL=-O2;-fmerge-all-constants
-- Found Numa: /usr/include  
-- Found Numa  (include: /usr/include, library: /usr/lib/libnuma.so)
-- OpenCV found (/usr/lib/cmake/opencv4)
-- Found FFMPEG or Libav: /usr/lib/libavcodec.so;/usr/lib/libavformat.so;/usr/lib/libavutil.so;/usr/lib/libswscale.so;/usr/lib/libswresample.so, /usr/include
Found FFMPEG/LibAV libraries
-- Using third party subdirectory Eigen.
-- Found PythonInterp: /usr/bin/python (found suitable version "3.9.4", minimum required is "3.0") 
-- Found PythonLibs: /usr/lib/libpython3.9.so.1.0 (found suitable version "3.9.4", minimum required is "3.0") 
CMake Warning at /usr/lib/python3.9/site-packages/pybind11/share/cmake/pybind11/pybind11Tools.cmake:19 (message):
  Set PYBIND11_PYTHON_VERSION to search for a specific version, not
  PYTHON_VERSION (which is an output).  Assuming that is what you meant to do
  and continuing anyway.
Call Stack (most recent call first):
  /usr/lib/python3.9/site-packages/pybind11/share/cmake/pybind11/pybind11Common.cmake:201 (include)
  /usr/lib/python3.9/site-packages/pybind11/share/cmake/pybind11/pybind11Config.cmake:249 (include)
  cmake/Dependencies.cmake:963 (find_package)
  CMakeLists.txt:513 (include)


-- Found PythonInterp: /usr/bin/python (found suitable version "3.9.4", minimum required is "3.9") 
-- Found PythonLibs: /usr/lib/libpython3.9.so.1.0
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Found pybind11: /usr/lib/python3.9/site-packages/pybind11/include (found version "2.6.2" )
-- System pybind11 found
-- pybind11 include dirs: /usr/lib/python3.9/site-packages/pybind11/include;/usr/include/python3.9
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
-- Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND) 
CMake Warning at cmake/Dependencies.cmake:1010 (message):
  Not compiling with MPI.  Suppress this warning with -DUSE_MPI=OFF
Call Stack (most recent call first):
  CMakeLists.txt:513 (include)


CMake Warning (dev) at /usr/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_C)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindOpenMP.cmake:565 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:1065 (find_package)
  CMakeLists.txt:513 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_CXX)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/Modules/FindOpenMP.cmake:565 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:1065 (find_package)
  CMakeLists.txt:513 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Adding OpenMP CXX_FLAGS: -fopenmp
-- Will link against OpenMP libraries: /usr/lib/libgomp.so;/usr/lib/libpthread.so
-- Found HIP: /opt/rocm/hip (found suitable version "4.1.21130-", minimum required is "1.0") 
HIP VERSION: 4.1.21130-

***** Library versions from dpkg *****


***** Library versions from cmake find_package *****

CMake Error at /usr/share/cmake-3.20/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindROCclr.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ROCclr", but
  CMake did not find one.

  Could not find a package configuration file provided by "ROCclr" with any
  of the following names:

    ROCclrConfig.cmake
    rocclr-config.cmake

  Add the installation prefix of "ROCclr" to CMAKE_PREFIX_PATH or set
  "ROCclr_DIR" to a directory containing one of the above files.  If "ROCclr"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /opt/rocm/hip/lib/cmake/hip/hip-config.cmake:128 (find_dependency)
  cmake/public/LoadHIP.cmake:131 (find_package)
  cmake/public/LoadHIP.cmake:171 (find_package_and_print_version)
  cmake/Dependencies.cmake:1154 (include)
  CMakeLists.txt:513 (include)


-- Configuring incomplete, errors occurred!
See also "/build/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/CMakeFiles/CMakeOutput.log".
See also "/build/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/CMakeFiles/CMakeError.log".
Building wheel torch-1.7.1
-- Building version 1.7.1
cmake -GNinja -DBUILD_BINARY=ON -DBUILD_CUSTOM_PROTOBUF=ON -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/build/python-pytorch-rocm/src/pytorch-1.7.1-rocm/torch -DCMAKE_PREFIX_PATH=/usr/lib/python3.9/site-packages -DCUDNN_INCLUDE_DIR=/usr/include -DCUDNN_LIBRARY=/usr/lib -DDISABLE_AVX2=1 -DDISABLE_AVX512F=1 -DDISABLE_FMA4=1 -DDISABLE_SSE4=1 -DNUMPY_INCLUDE_DIR=/usr/lib/python3.9/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/usr/bin/python -DPYTHON_INCLUDE_DIR=/usr/include/python3.9 -DPYTHON_LIBRARY=/usr/lib/libpython3.9.so.1.0 -DTORCH_BUILD_VERSION=1.7.1 -DUSE_CUDA=OFF -DUSE_FFMPEG=ON -DUSE_GFLAGS=ON -DUSE_GLOG=ON -DUSE_MKLDNN=ON -DUSE_NUMPY=True -DUSE_OPENCV=ON -DUSE_ROCM=ON -DUSE_SYSTEM_NCCL=ON /build/python-pytorch-rocm/src/pytorch-1.7.1-rocm
Traceback (most recent call last):
  File "/build/python-pytorch-rocm/src/pytorch-1.7.1-rocm/setup.py", line 760, in <module>
    build_deps()
  File "/build/python-pytorch-rocm/src/pytorch-1.7.1-rocm/setup.py", line 310, in build_deps
    build_caffe2(version=version,
  File "/build/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/build_pytorch_libs.py", line 54, in build_caffe2
    cmake.generate(version,
  File "/build/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/setup_helpers/cmake.py", line 333, in generate
    self.run(args, env=my_env)
  File "/build/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBUILD_BINARY=ON', '-DBUILD_CUSTOM_PROTOBUF=ON', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/build/python-pytorch-rocm/src/pytorch-1.7.1-rocm/torch', '-DCMAKE_PREFIX_PATH=/usr/lib/python3.9/site-packages', '-DCUDNN_INCLUDE_DIR=/usr/include', '-DCUDNN_LIBRARY=/usr/lib', '-DDISABLE_AVX2=1', '-DDISABLE_AVX512F=1', '-DDISABLE_FMA4=1', '-DDISABLE_SSE4=1', '-DNUMPY_INCLUDE_DIR=/usr/lib/python3.9/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/usr/bin/python', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.9', '-DPYTHON_LIBRARY=/usr/lib/libpython3.9.so.1.0', '-DTORCH_BUILD_VERSION=1.7.1', '-DUSE_CUDA=OFF', '-DUSE_FFMPEG=ON', '-DUSE_GFLAGS=ON', '-DUSE_GLOG=ON', '-DUSE_MKLDNN=ON', '-DUSE_NUMPY=True', '-DUSE_OPENCV=ON', '-DUSE_ROCM=ON', '-DUSE_SYSTEM_NCCL=ON', '/build/python-pytorch-rocm/src/pytorch-1.7.1-rocm']' returned non-zero exit status 1.
==> ERROR: A failure occurred in build().
    Aborting...
```
I've tried add `rocclr` as a dependency and it will still happen.

**Comment by Thorhian** [comment] 2021-07-11 00:44
I had the same problem yesterday and today. I got past this error by exporting a env variable:
`export ROCclr_DIR=/opt/rocm/lib/cmake/rocclr`

However, I then encountered this error. Maybe I should look at the issues for this other problem.
[rocm-ninja-error.txt](https://github.com/rocm-arch/python-pytorch-rocm/files/6796144/rocm-ninja-error.txt)

**Comment by silago** [comment] 2021-07-11 17:40
@Thorhian I believe you have a file called like libamdhip64.so.x.x.21240-3175bb0 you can make a link to

**Comment by Thorhian** [comment] 2021-07-11 18:02
Thanks @silago, but since the rest of the ROCm compiled and seemed to run properly I just used the wheel build directly from pytorch's website using PIP along with torch vision. Thankfully it worked just fine and I haven't had any errors sending tensors to the GPU yet. I'll keep your advice in mind though. The build script seems to need a bit of maintenance though lol. I wish I knew more about how to fix these kinds of crazy build systems. Still a noob.

**Comment by xdrie** [comment] 2021-08-12 21:54
I had the same issue as @Thorhian initially, the export also gave me the ninja error, and

So just adding another voice to confirm that this works.

**Comment by acxz** [comment] 2022-02-21 02:58
Closing this error as I cannot reproduce it and it has been a while since the last report. Feel free to open it if you are still facing this issue.

**Closed by acxz** 2022-02-21 02:58 UTC
Labels: build error
