### ISSUE TITLE
Build failed at [3827/4843] in the latest release.

### ISSUE THREAD

**Issue by takfate** [rocm-arch/python-pytorch-rocm#15] opened 2020-12-24 16:40 UTC
error log follows:
```
[3827/4843] cd /var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated && /usr/bin/cmake -E make_directory /var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/. && /usr/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=RELEASE -D generated_file:STRING=/var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/./torch_hip_generated_THHTensorMaskedShort.hip.o -P /var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2/CMakeFiles/torch_hip.dir/__/aten/src/THH/generated/torch_hip_generated_THHTensorMaskedShort.hip.o.cmake
ninja: build stopped: subcommand failed.
Building wheel torch-1.7.1
-- Building version 1.7.1
cmake -GNinja -DBUILD_BINARY=ON -DBUILD_CUSTOM_PROTOBUF=ON -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/torch -DCMAKE_PREFIX_PATH=/usr/lib/python3.8/site-packages -DCUDNN_INCLUDE_DIR=/usr/include -DCUDNN_LIBRARY=/usr/lib -DDISABLE_AVX2=1 -DDISABLE_AVX512F=1 -DDISABLE_FMA4=1 -DDISABLE_SSE4=1 -DNUMPY_INCLUDE_DIR=/usr/lib/python3.8/site-packages/numpy/core/include -DPYTHON_EXECUTABLE=/usr/bin/python -DPYTHON_INCLUDE_DIR=/usr/include/python3.8 -DPYTHON_LIBRARY=/usr/lib/libpython3.8.so.1.0 -DTORCH_BUILD_VERSION=1.7.1 -DUSE_CUDA=OFF -DUSE_FFMPEG=ON -DUSE_GFLAGS=ON -DUSE_GLOG=ON -DUSE_MKLDNN=ON -DUSE_NUMPY=True -DUSE_OPENCV=ON -DUSE_ROCM=ON -DUSE_SYSTEM_NCCL=ON /var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm
cmake --build . --target install --config Release -- -j 16
Traceback (most recent call last):
  File "setup.py", line 760, in <module>
    build_deps()
  File "setup.py", line 310, in build_deps
    build_caffe2(version=version,
  File "/var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/setup_helpers/cmake.py", line 349, in build
    self.run(build_args, my_env)
  File "/var/tmp/pamac-build-tak/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '16']' returned non-zero exit status 1.
==> ERROR: A failure occurred in build().
    Aborting...


```

**Comment by acxz** [comment] 2020-12-24 16:56
hmm I can't seem to reproduce this. Can you confirm if you have all the updated dependencies from the AUR? Note: The arch4edu binaries are prob lagging a bit rn, since we just updated to rocm 4.0.

It also seems that your python version is outdated. Please do a `pacman -Syu` to get python39, not that I think that is the issue, but good practice nonetheless. Please post your error once you have updated your outdated system.

**Comment by takfate** [comment] 2020-12-25 15:50
I have installed the latest and clean `manjaro` system environment.I try to build and install the latest `python-pytorch-opt-rocm` package. the previous errors no longer occur. but the package build failed at [4446/4780]. error log follows:
```
[4446/4780] Building CXX object test_api/CMakeFiles/test_api.dir/modules.cpp.o
cc1plus: warning: command-line option ‘-Wno-duplicate-decl-specifier’ is valid for C/ObjC but not for C++
cc1plus: note: unrecognized command-line option ‘-Wno-implicit-int-float-conversion’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-unused-command-line-argument’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-exceptions’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-inconsistent-missing-override’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-macro-redefined’ may have been intended to silence earlier diagnostics
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 760, in <module>
    build_deps()
  File "setup.py", line 310, in build_deps
    build_caffe2(version=version,
  File "/home/tak/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/tak/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/setup_helpers/cmake.py", line 349, in build
    self.run(build_args, my_env)
  File "/home/tak/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '16']' returned non-zero exit status 1.
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by acxz** [comment] 2020-12-25 17:58
> I have installed the latest and clean manjaro system environment.

ahh that's probably why. It would have been great if you could have mentioned that earlier. Manjaro doesn't support the AUR and neither do we support Manjaro. I'm afraid you won't be able to use this package on a distribution other than an Arch-based one. By Arch-based I mean, one to one repo compatible which Manjaro is not, since they lag behind package updates.

Take a look at [EndeavourOS](https://endeavouros.com/) if you want a easy to install Arch distribution which is one to one repo compatible and hence a distribution that we support.

Closing this issue as `Manjaro not supported`

**Closed by acxz** 2020-12-25 17:58 UTC
