### ISSUE TITLE
All operations on cuda device fail with hipErrorLaunchFailure

### ISSUE THREAD

**Issue by mikesbytes** [rocm-arch/python-pytorch-rocm#41] opened 2022-04-17 07:37 UTC
It seems that any torch operations I try to run with `cuda` device error out with `hipErrorLaunchFailure`

## Reproduction steps

I run this code:

```
import torch

device = torch.device("cuda")
a = torch.randn(100, device=device, dtype=torch.float)
print(a)
````
I receive

```
RuntimeError: HIP error: hipErrorLaunchFailure
```

on the `randn` line.

## System Info

`rocminfo`

```
ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 9 5950X 16-Core Processor
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen 9 5950X 16-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3400                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    65766776(0x3eb8578) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    65766776(0x3eb8578) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65766776(0x3eb8578) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1030                            
  Uuid:                    GPU-XX                             
  Marketing Name:          AMD Radeon RX 6900 XT              
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      4096(0x1000) KB                    
    L3:                      131072(0x20000) KB                 
  Chip ID:                 29631(0x73bf)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   2660                               
  BDFID:                   2048                               
  Internal Node ID:        1                                  
  Compute Unit:            80                                 
  SIMDs per CU:            2                                  
  Shader Engines:          8                                  
  Shader Arrs. per Eng.:   2                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          32(0x20)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    1024(0x400)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16760832(0xffc000) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1030         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***             
```

`hipconfig --full`

```
HIP version  : 5.1.20531-409cba2

== hipconfig
HIP_PATH     : /opt/rocm/hip
ROCM_PATH    : /opt/rocm
HIP_COMPILER : clang
HIP_PLATFORM : amd
HIP_RUNTIME  : rocclr
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__= -D__HIP_PLATFORM_AMD__= -I/opt/rocm/hip/include -I/opt/rocm/llvm/bin/../lib/clang/14.0.0 -I/opt/rocm/hsa/include

== hip-clang
HSA_PATH         : /opt/rocm/hsa
HIP_CLANG_PATH   : /opt/rocm/llvm/bin
clang version 14.0.0 (https://aur.archlinux.org/rocm-llvm 7cfd2f24ab4d7d33950eaf0570d7fb7f04f9e07a)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
AOMP-12.0-3 (http://github.com/ROCm-Developer-Tools/aomp):
 Source ID:12.0-3-bebd719ff2bb58a4220658c708f91d486729dbc1
  LLVM version 14.0.0git
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: znver3

  Registered Targets:
    amdgcn - AMD GCN GPUs
    r600   - AMD GPUs HD2XXX-HD6XXX
    x86    - 32-bit X86: Pentium-Pro and above
    x86-64 - 64-bit X86: EM64T and AMD64
hip-clang-cxxflags :  -std=c++11 -isystem "/opt/rocm/llvm/lib/clang/14.0.0/include/.." -isystem /opt/rocm/hsa/include -isystem "/opt/rocm/hip/include" -O3
hip-clang-ldflags  :  -L"/opt/rocm/hip/lib" -O3 -lgcc_s -lgcc -lpthread -lm -lrt

=== Environment Variables
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

== Linux Kernel
Hostname     : Can't exec "hostname": No such file or directory at /usr/bin//hipconfig.pl line 218.
Linux ryuko 5.17.2-zen3-1-zen #1 ZEN SMP PREEMPT Sun, 10 Apr 2022 11:18:34 +0000 x86_64 GNU/Linux
LSB Version:	n/a
Distributor ID:	Arch
Description:	Arch Linux
Release:	rolling
Codename:	n/a
```

I am running freshly built 5.1.1 packages. I'm very new to GPGPU programming so I'm not really sure what other diagnostics are needed here.

**Comment by JP-Ellis** [comment] 2022-04-17 08:28
Since you were able to build everything but there weren't able to run it, I am curious to see whether you are able to run it in other cases.

Would you mind trying to run the same code snippet you included above within the [`rocm/pytorch` Docker image](https://hub.docker.com/r/rocm/pytorch)?

**Comment by mikesbytes** [comment] 2022-04-17 16:05
Just tried it, my example does work in the docker container

**Comment by wuxxin** [comment] 2022-04-20 01:14
i currently experience the same issue (gfx1030), on calling:
```sh
HIP_LAUNCH_BLOCKING=1 AMD_LOG_LEVEL=3 \
  python -c "import torch;device=torch.device('cuda:0');a=torch.randn(100,device=device,dtype=torch.float);print(a)"
```

the probably relevant error output is:
```log
ihipModuleLaunchKernel ( 0x0x560f6da581e0, 256, 1, 1, 256, 1, 1, 0, stream:<null>, 0x7ffe7cbfaf10, char array:<null>, event:0, event:0, 0, 0 )
Launch params (256, 1, 1) are larger than launch bounds (128) for kernel _ZN2at6native6modern18elementwise_kernelINS0_10AbsFunctorIfEENS_6detail5ArrayIPcLi2EEEEEviT_T0_
```

to get the debug output, use `AMD_LOG_LEVEL=3`, see https://docs.amd.com/bundle/AMD_HIP_Programming_Guide/page/Programming_with_HIP.html

**Comment by wuxxin** [comment] 2022-07-04 11:08
@JP-Ellis there were lot of changes for the navi21 chip in the amd fork of pytorch which went into the "official" amd binaries, (something connected to warpsize). My guess was they are probably incorporated and resolved with 1.12.

i will try to build and test 1.12 today, or tomorrow and write the results.

**Comment by wuxxin** [comment] 2022-07-06 14:42
i can report success executing
```
python -c "import torch; d=torch.device('cuda:0')
   a=torch.randn(100,device=d,dtype=torch.float); print(a)"
```
using python-pytorch-rocm 1.12.0-2 on gfx1030 (Radeon Pro W6800)

**Comment by acxz** [comment] 2022-07-06 14:50
I am stoked!!!!!!!

**Comment by acxz** [comment] 2022-07-06 15:01
@mikesbytes can you confirm the issue is resolved? Otherwise, I'll close this in a couple of days. Feel free to open it up if you still experience the issue.

**Closed** 2022-07-06 21:36 UTC
Labels: runtime error
